# Generated by Django 4.0.4 on 2022-06-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_categoryoffer_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
