# Generated by Django 4.0.4 on 2022-06-26 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_rename_active_productoffer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(75)]),
        ),
    ]
