# Generated by Django 4.0.4 on 2022-06-01 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid name', regex='^[A-Za-z][A-Za-z ]*$'), django.core.validators.MinLengthValidator(3, 'Min 3 char required')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid name', regex='^[A-Za-z][A-Za-z ]*$'), django.core.validators.MinLengthValidator(3, 'Min 3 char required')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')]),
        ),
    ]
