# Generated by Django 4.0.4 on 2022-06-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddresses',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
