# Generated by Django 4.0.4 on 2022-06-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraddresses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddresses',
            name='user',
        ),
    ]
