# Generated by Django 4.0.4 on 2022-06-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
    ]
