# Generated by Django 3.2.13 on 2022-07-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
